name: test_project
source: ./static/css/test.css
format: yaml
dest: ./docs
dependencies: ./static
layout_template: ./layout_template
timestamp_format: YYYY/MM/DD/ HH:mm
# highlight: false
highlight_theme: duotone-light
  # dark  [monokai, dracula, seti]
  # light [duotone-light, on-light]
md_class: 
  heading:
    - hoge
  listitem:
    - hogehoge
inject:
  - html  
  - jade  
  - js    
  - coffee
highlight: false
