name: test_project
source: ./static/css/test.css
format: yaml
dest: ./docs
dependencies: ./static
template: ./template
timestamp_format: YYYY/MM/DD/ HH:mm
highlight_theme: dracula
md_class: 
  heading:
    - hoge
  listitem:
    - hogehoge
inject:
  - html  
  - jade  
  - js    
  - coffee
highlight: false
