name: Example Styleguide
source: ./doc_assets/styles
dest: ./styleguide
dependencies:
  - ./doc_assets
module_dir: ./html
index: ./index.md
#dest: ./styleguide_jade
#template_dir: ./template_jade
#template_engine: jade
