source: ./doc
source_type: .md
template_engine: ejs
template_dir: ./template
dest: ../docs
dependencies: ./doc_assets
index: ./doc/index.md
log: true
transform: [ejs]
color_palette: false
disable_index: true
